name: Karate Web App Testing
on:
  push:
jobs:
  Testing-Karate-Demo:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Execute the Tests
        run :  docker run --rm -d -v ${PWD}:/usr/src/test -w /usr/src/test markhobson/maven-chrome:jdk-21 mvn test

      - run: echo "🍏 This job's status is ${{ job.status }}."